### PR TITLE
Grant the reader show access to an associated submission

### LINKED ISSUE #395: ETD Reader unable to view ETD PDF for Dissertation ID: 0000012075
I was just contacted by the Registrar, who received a ServiceNow ticket regarding Dissertation ID: 0000012075 as described below:

Ticket submitted by: Young Lee (Primary Advisor)

SUID Number: 5927170

I am trying to review the submitted PhD dissertation of my advisee (Aaron Breidenbach) on Axess. However, I get an error when I click on the thesis link (saying that I am not authorized to view it).

Image

*********
Emma just added, that while I was recently on vacation the following occurred, and maybe it is related?

The issue Ron reported sounds the same as this one: https://stanfordlib.slack.com/archives/C3X3D811A/p1759420236614939. I'm not sure what Michael ended up having that user do.

Michael Olson
@here.  Good morning.  We've got a ETD reader that is having issues with reading the PDF.  I can't find anything wrong with the following.  Is someone available to have a look and make sure I"m not missing anything?  Here's what I'm trying to troubleshoot.
A final reader is trying to approve ETD 12067, but is encountering an error when clicking on the PDF link.
https://etd.stanford.edu/submissions/0000012067/reader_review

### PR DESCRIPTION
**Pull request by mjgiarlo**
Fixes #395

This lets them get at the dissertation PDF.

### CODE REVIEW

File: app/policies/submission_policy.rb [hunk 1]
```diff
@@ -7,7 +7,7 @@ class SubmissionPolicy < ApplicationPolicy
   alias_rule :edit?, :submit?, :review?, :attach_supplemental_files?, :attach_permission_files?, to: :update?
 
   def show?
-    author? || admin?
+    author? || admin? || (reader? && record.submitted?)
```
Comment (mjgiarlo) [inline app/policies/submission_policy.rb]: Somehow, we'd missed porting this from hydra_etd, apparently.
